### ISSUE TITLE
Example for auth0-react

### ISSUE THREAD

**Issue by dillonco** [adamjmcgrath/cypress-spa-example#2]
I was following along with this bug [ticket](https://github.com/auth0/auth0-spa-js/issues/581) because we're in a near identical situation and tried implementing the solutions you have here but we couldn't get the `isAuthenticated` to ever return True. 
The only difference that I can tell is that we use the [Auth0-React](https://github.com/auth0/auth0-react) package instead of the SPA one.

With that said do they both work in the same way now, by storing tokens in session storage? 
and would you know of anything to change from the sample code you have here to support the Auth0-react package?

**Comment by adamjmcgrath** [comment]
Hey @dillonco - using auth0-react shouldn't make a difference since it's using spa js under the hood

> we couldn't get the isAuthenticated to ever return True.

This is usually a mismatch between what you're saving to localStorage in your Cypress code (which should look something like https://github.com/adamjmcgrath/cypress-spa-example/blob/master/cypress/integration/example.spec.js#L33) and what auth0-react (via spa js) is looking for in localStorage when it checks if you're authenticated.

To debug, put something like this at the top of your page

```html
<script>
    var __getItem = localStorage.getItem.bind(localStorage);
    localStorage.getItem = function (key) {
      console.log('looking for', key, 'in', Object.keys(localStorage));
      return __getItem(key);
    };
  </script>
```

This should log something like this to your console:

`looking for @@auth0spajs@@::xyzabc::default::openid profile email in ["@@auth0spajs@@::xyzabc::default::openid profile email", "ally-supports-cache"]`


The cache key format is `@@auth0spajs@@::CLIENT_ID::AUDIENCE::SCOPE`, if the key your looking for doesn't quite match the one in the list - you'll need to update the CLIENT_ID, AUDIENCE or SCOPE in your Cypress code or where you've invoked `<Auth0Provider>`

If the list doesn't have anything like that in it, you haven't logged in succesfully.

If the console doesn't log anything, check you're using `cacheLocation="localstorage"` in your `Auth0Provider` (you need to do this at least under test)

**Comment by dillonco** [comment]
That's exactly what I needed to know, thank you!
